feat: add functionality
krlktv/task-tracker pull request #1
Opened 2021-07-13 14:50 UTC by krlktv

All tasks are displayed in the corresponding list (ToDo or Completed). 
Ability to create a task. 
Ability to edit the task. 
Ability to delete a task. 
Ability to mark a task as completed (a completed task cannot be edited). 
Sorting by creation date (from new to old and vice versa). 
Assigning a specific color to each task. 
The number of incomplete and completed tasks in parentheses behind the title of the section with tasks. 
Saving tasks (using localStorage).

2021-07-20 16:25 UTC, maximsan requested changes
Hello. I left some note, let's discuss your implementation later

2021-07-20 16:25 UTC, maximsan commented on app.js
> +		renderTasks();
it can be a reusable method

2021-07-20 16:25 UTC, maximsan commented on app.js
> +		renderTasks();
it can be a reusable method

2021-07-20 16:25 UTC, maximsan commented on app.js
> +		currentEditId = id;
it can be a reusable method

2021-07-20 16:25 UTC, maximsan commented on app.js
> +	const addTaskHigh = document.querySelector('#High').checked;
try to use class selectors for such trivial cases

2021-07-20 16:25 UTC, maximsan commented on app.js
> +		priority = 'Low';
create dictionary for priorities

2021-07-20 17:02 UTC, maximsan requested changes
I left some more notes. Please review, let me know if you have questions. Thanks!

2021-07-20 17:02 UTC, maximsan commented on app.js
> +			task.className = `list-group-item d-flex w-100 mb-2 ${color}`;
create method `createTaskClassName`

2021-07-20 17:02 UTC, maximsan commented on app.js
> +	}
use ternary operator

2021-07-21 16:35 UTC, Dev1LtJ requested changes
Hello! Excellent work. I left some comments. Try to answer on it all.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +const incr = document.querySelector('#incr');
Create semantic names for your variables.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +const decr = document.querySelector('#decr');
Create semantic names for your variables.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +const clearAll = document.querySelector('#clearAll');
Create semantic names for your variables.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +});
Rework it with on method

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +});
What if i want to create new tasks after clearance with reverted sequence?

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +'use strict';
You don't need it, coz you are using class constructor.  It's automatically enables 'use strict'.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +		priority = 'Low';
You can use querySelectorAll and find the checked field.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +}
Rework your data flow, as Maxim said.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +}
I think it's better to rerender only part, that you need.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +	if (localStorage.getItem(0) === 'incr') {
Rework your data flow

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +			tasksArray.push(JSON.parse(localStorage.getItem(i)));
Rework your data flow

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +		`;
I think better way is to create a copy of element, that you have in template and fill it, coz if template will be changed your component wouldn't be match it.

2021-07-21 16:35 UTC, Dev1LtJ commented on app.js
> +	const task = JSON.parse(localStorage.getItem(currentEditId));
I think it's bad approach every time to use local storage.

2021-07-23 12:17 UTC, krlktv commented on app.js
> +	localStorage.setItem(0, 'incr');
Thanks. I fixed it.
Removed the conditional construct.

2021-07-23 12:28 UTC, krlktv commented on app.js
> +		renderTasks();
Thanks. I refactored it.
```suggestion
		render();
```

2021-07-23 12:29 UTC, krlktv commented on app.js
> +		renderTasks();
Thanks. I refactored it.
```suggestion
		render();
```

2021-07-23 12:46 UTC, krlktv commented on app.js
> +		currentEditId = id;
Thanks. I refactored it.
```suggestion
		const id = getTaskId(e);
		fillTaskData(id);
		currentEditId = id;
```

2021-07-23 13:07 UTC, krlktv commented on app.js
> +		day = '0' + day;
Thanks. I refactored it.
```suggestion
		day = `0${day};
```

2021-07-23 13:21 UTC, krlktv commented on app.js
> +	if (localStorage.getItem(0) === 'incr') {
Thanks. I refactored it.
```suggestion
	if (localStorage.getItem(0) === SORTING.asc) {
```

2021-07-23 13:33 UTC, krlktv commented on app.js
> +	} else if (localStorage.getItem(0) === 'decr') {
Thanks. I refactored it.
```suggestion
	} else if (sortingValue === SORTING.desc) {
```

2021-07-24 14:45 UTC, krlktv commented on app.js
> +		priority = 'Low';
Thanks. I fixed it.
```suggestion
		priority = PRIORITY.low;
```

2021-07-26 09:47 UTC, krlktv commented on app.js
> +			task.className = `list-group-item d-flex w-100 mb-2 ${color}`;
Thanks. I added it.
```suggestion
			task.className = createTaskClassName(color);
```

2021-07-26 11:02 UTC, krlktv commented on app.js
> +	const addTaskHigh = document.querySelector('#High').checked;
Thank you! 
I will use class selectors for such trivial cases in the future. 
In this case IDs are also needed to bind to the label tag in markup.

2021-07-26 11:23 UTC, krlktv commented on app.js
> +		`;
Thanks. I fixed it.
```suggestion
		task.innerHTML = createTaskTemplate(current.title, current.priority, current.date, current.text, editBtn);
```

2021-07-26 11:29 UTC, krlktv commented on app.js
> +			}
Thanks. I refactored it.
```suggestion
			const editBtn = !current.isCompleted ? editButton : '';
```

2021-07-26 11:32 UTC, krlktv commented on app.js
> +	}
Thanks. I fixed it.
```suggestion
	task.isCompleted = !task.isCompleted ? true : false;
```

2021-07-26 11:36 UTC, krlktv commented on app.js
> +const incr = document.querySelector('#incr');
```suggestion
const ascBtn = document.querySelector('#incr');
```

2021-07-26 11:37 UTC, krlktv commented on app.js
> +const decr = document.querySelector('#decr');
Thanks. I fixed it.
```suggestion
const descBtn = document.querySelector('#decr');
```

2021-07-26 11:37 UTC, krlktv commented on app.js
> +const clearAll = document.querySelector('#clearAll');
Thanks. I fixed it.
```suggestion
const clearAllBtn = document.querySelector('#clearAll');
```

2021-07-26 12:18 UTC, krlktv commented on app.js
> +});
Thanks. I fixed it.
```suggestion
localStorage.setItem(0, sortingValue);
```

2021-07-26 12:25 UTC, krlktv commented on app.js
> +'use strict';
Yes, all code inside the class construct is automatically in strict mode, but not for the whole js file. Thanks!

2021-07-26 12:30 UTC, krlktv commented on app.js
> +}
Only tasks are rerender here, the rest of the page is not rerender. Thanks!

2021-07-26 12:33 UTC, krlktv commented on app.js
> +		`;
Thanks. I fixed it.
```suggestion
		task.innerHTML = createTaskTemplate(current.title, current.priority, current.date, current.text, editBtn);
```

2021-07-26 12:40 UTC, krlktv commented on app.js
> +});
Thanks. I fixed it.
```suggestion
ascBtn.addEventListener('click', () => {
	setSorting(SORTING.asc);
	render();
});

descBtn.addEventListener('click', () => {
	setSorting(SORTING.desc);
	render();
});
```

2021-07-26 13:30 UTC, krlktv commented on app.js
> +	if (localStorage.getItem(0) === 'incr') {
Thanks. I fixed it.
```suggestion
	if (sortingValue === SORTING.asc) {
```

2021-07-26 13:34 UTC, krlktv commented on app.js
> +	const task = JSON.parse(localStorage.getItem(currentEditId));
Thank you!
I will take this fact into account and try to rework the interaction with local storage.

2021-07-27 07:55 UTC, krlktv commented on app.js
> +		priority = 'Low';
Thanks. I'll try to fix it.

2021-07-27 07:55 UTC, krlktv commented on app.js
> +}
Thanks. I'll try to fix it.

2021-07-28 16:34 UTC, maximsan requested changes
It looks better. I left some comments. Let me know if you have questions!

2021-07-28 16:34 UTC, maximsan commented on index.html
> +			color: #fff !important;
don't use `!important`

2021-07-28 16:34 UTC, maximsan commented on app.js
> +		if (current === null) {
`if(!current)`

2021-07-28 16:34 UTC, maximsan commented on app.js
> +	}
create method `sortBy(value)` for this. The method  should be simpler than your implementation

2021-07-30 09:06 UTC, maximsan commented on app.js
> +			tasksArray.push(JSON.parse(localStorage.getItem(i)));
@Dev1LtJ please give more details about what you mean. That's not enough to leave a note that it should be reworked. You have to give an insight about what exactly should be changed or propose something or leave a peace of code.

2021-07-30 09:27 UTC, krlktv commented on app.js
> +		if (current === null) {
Thanks. I fixed it.
```suggestion
		if (!current) {
```

2021-07-31 14:59 UTC, krlktv commented on app.js
> +	}
Thanks. I fixed it.
```suggestion
	const tasksArray = sortBy(sortingValue);
```

2021-08-02 08:44 UTC, krlktv commented on index.html
> +			color: #fff !important;
Yes, I know this is bad practice. Here I use it to change bootstrap styles.
In the future, I will not use `!important`.

2021-08-03 19:24 UTC, Dev1LtJ requested changes
Good work! Read my comments and try to fix your data flow.

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +	}
rework it with forEach method and take only checked button.

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +}
You should to rerender only part, that you really need (uncompleted or completed tasks list).

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +function toTaskDate(taskDate) {
taskDateToString

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +	}
Rework:
1) Data flow (unnecessary continue);
2) Task priority class. Your priority - is your class.

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +			const editBtn = !current.isCompleted ? editButton : '';
Choice correct name and hide button (do not switch it to empty string).

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +			task.innerHTML = createTaskTemplate(current.title, current.priority, current.date, current.text, editBtn);
createTaskHTML

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +	const editModal = document.querySelector('#editModal');
Create it with one modal and hide edit or create button

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +	}
Rework it with same name of priority and class (or name or data- or smthg else). Your code will be like: ...querySelector(`${task.priority}`).checked = true;

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +	}
look previous comment.

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +}
As i said, in this case is better to crete copy of an template element, which created for your by author.

2021-08-03 19:24 UTC, Dev1LtJ commented on app.js
> +function setSorting(value) {
setSortType

2021-09-08 14:00 UTC, merged